---
title: "MLST"
author: "Shuai Man"
date: "2024-06-17"
# This R script provides a bidirectional conversion tool for handling Multi-Locus Sequence Typing (MLST) data. It can convert between individual FASTA sequence files and a consolidated Excel spreadsheet format, making it easier to manage and analyze sequence data for phylogenetic studies
---
```{r}
# Used for from individual sequence file to a spreadsheet
library(seqinr)
library(writexl)
install.packages("writexl")

# Set the directory containing the sequence files
input_dir <- read_excel("/Users/sm2259/Desktop/MLST/Concatenate_Sequence.xlsx", sheet = "Sheet1")


# Get a list of all the sequence files in the directory
sequence_files <- list.files(input_dir, pattern = "\\.fasta$", full.names = TRUE)

# Initialize an empty data frame to store the results
results <- data.frame(FSL_Number = character(), Description = character(), ITS_Sequence = character(), stringsAsFactors = FALSE)

# Iterate over each sequence file
for (file in sequence_files) {
  # Read the contents of the file
  fasta_entry <- readLines(file)
  
 # Extract the SampleID from the header line
header <- fasta_entry[1]
sample_id <- as.numeric(sub("^>(\\S+).*", "\\1", header))
  
  
  # Extract the sanger sequence (assuming it starts from the second line)
  sanger_sequence <- paste(fasta_entry[-1], collapse = "")
  
  # Add the extracted information to the results data frame
  results <- rbind(results, data.frame(SampleID = sample_id, Sanger_Sequence =sanger_sequence, stringsAsFactors = FALSE))
}

# Write the results to an Excel file
output_file <- "ITS_Sanger_Sequence_Output.xlsx"
write_xlsx(results, output_file)

```


```{r}
#From spreadsheet to sequences file
# Load required packages
library(readxl)
library(stringr)

# Load the Excel file
excel_data <- read_excel("/Users/sm2259/Desktop/MLST/Concatenate_Sequence.xlsx", sheet = "Sheet2")

# Create a directory to store the output files
output_dir <- "ThreeLoci_Sequence_files"
dir.create(output_dir, showWarnings = FALSE)

# Iterate over each row
for (i in 1:nrow(excel_data)) {
  # Extract the FSL number, sequence, and description for the current row
  fsl_number <- excel_data$FSL_Number[i]
  sequence <- excel_data$Concatenate_Sequence[i]
  description <- excel_data$Description[i]
  
  # Format the FSL number, sequence, and description into FASTA format
  fasta_entry <- paste0(">", fsl_number, " ", description, "\n", sequence)
  
  # Create a filename for the output file
  filename <- paste0(fsl_number, ".fasta")
  filepath <- file.path(output_dir, filename)
  
  # Write the FASTA entry to the output file
  writeLines(fasta_entry, filepath)
}

cat("Export completed.\n")
```

